# Generated by Django 4.2.1 on 2023-12-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_product_in_price_avg_product_in_price_near_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
