# Generated by Django 5.0 on 2024-01-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_employee_saleorder_saleorderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='full_name',
            new_name='name',
        ),
    ]
