# Generated by Django 5.0 on 2024-01-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_worktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='bonus',
            field=models.BooleanField(default=False),
        ),
    ]
