# Generated by Django 5.0 on 2024-01-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_worktime_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
