# Generated by Django 5.0 on 2024-02-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderdetail',
            name='in_price',
            field=models.FloatField(default=0),
        ),
    ]
